name: hackademics.io.v1 build
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build hackademics.io.v1
        run: |
          yarn
          npm run build
